### PR TITLE
Begin logging

### LINKED ISSUE #67: Log files
We'll be using Florian's approach to logfiles for the touch table. 

#### General
- [ ] Clicking ‘start’ to open classifier (`Open_Classifier`)
- [ ] Closing a classifier 

#### Galaxy Interaction
- [ ] Dragging a galaxy from the center (`Drag_Galaxy`)
- [ ] Dropping a galaxy into a classifier (`Drop_Galaxy`)
- [ ] Pressing the "move map" button (`Move_Map`)

#### Example (help) panel
- [x] ~Opening the example panel~ (panel will remain open)
- [x] ~Closing the example panel~ (panel will remain open)
- [ ] Scrolling to the bottom of a description (`Scroll_To_Bottom`)
- [ ] Selecting a galaxy example to examine (`Selected_Galaxy_Example`)

#### Notifications
- [ ] Clicking on an ‘Ask a neighbor’ icon (`Ask_For_Help`)
     **Context:**
     - User asked successfully received request for help (`Request_Sent`)
     - User asked is busy helping another person at the table (`User_Busy`)
     - User asked is currently working with user (`Already_Helping`)
     - User asked is not currently at the table (`User_Unavailable`)
     - User asked has already been asked for help (`Already_Asked`)
     - User asked has already seen the current subject (`Already_Seen`)
     - User must respond to current help request before asking another for help (`Pending_Request`)
     - User does not currently have a subject (`Drag_To_Begin`)
- [ ] Clicking "accept galaxy" to accept an invitation to help another user (`Accept_Galaxy`)
- [ ] Clicking "decline galaxy" to decline an invitation to help another user (`Decline_Galaxy`)
- [ ] User classified a galaxy another user needed help with (`Helped_User`)

#### Close Classifier Modal
- [ ] Clicking on ‘intent’ button (whether intend to continue effort online) (`Intent`)
- [ ] Pressing "Close & End" to close the classifier (`Close_And_End`)
- [ ] Pressing "Keep classifying" or "cancel" to continue session without closing classifier (`Keep_Classifying`) (`Hide_Close_Confirmation`)

#### Still There? Modal
- [ ] User presses "continue classifying" button to continue work (`Dismiss_Still_There`)
- [ ] User presses "close now" to end session (`Close_From_Still_There`)
- [ ] Classifier closes due to timeout (`Close_Timeout`)

#### Classifier
- [ ] "Submit Classification" button to classify a galaxy (`Submit_Classification`)
- [ ] "Random galaxy" button to choose a random galaxy to classify next (`Random_Galaxy`)
- [ ] "Choose another galaxy" button to choose another galaxy to drag into the classifier (`Choose_Galaxy`)

#### Leveler ( tracking classification counts to the right of the classification panel)
- [ ] Press to open the leveler (`Toggle_Leveler`)

### Intermediate page Using Google Analytics
- [ ] Click on ‘go to galaxy zoo’ 
- [ ] Click on ‘go to zooniverse.org’
- [ ] Click on ‘register’
- [ ] Visits to intermediate page
- [ ] User scrolls past top of page
- [ ] User scrolls to bottom

### PR DESCRIPTION
**Pull request by wgranger**
Describe your changes.
This PR adds logging to the touch table app. In total, there are six items we are logging, reflected by the headers in the log file csv. The six items are:
entry, user, subjectId, state, context, time

A couple other bugs were also resolved in this PR.

Closes #67 

# Review Checklist

- [x] Are tests passing?
- [x] Is the build free of output errors?

### CODE REVIEW

**Comment by chelseatroy** [comment]
Sweet. Should I look for the logs in the console, or are we sending those to a specific file or other place?

**Comment by wgranger** [comment]
Good question. I should add this to the README. Logs are but into the `bin/debug` folder, since we're using staging. They won't appear while debugging unless you close the program with the "X," as opposed to stopping the debug session from visual studio.

**Comment by wgranger** [comment]
But... I'm not sure how this will work when the app is installed on the table since there won't be a `bin`. Maybe I should put them into a "special location" like documents, or another path.

**Comment by chelseatroy** [comment]
That'd be my main comment on this. I can see them on my machine of course, but I imagine we'll want to be able to get to them if something happens on the table itself. I'm happy to merge this in as a progress point, though. What do you think—merge it in and open a new one to change the log location, or do it on this one?

**Comment by wgranger** [comment]
No. I'll make the change on this PR.

**Comment by wgranger** [comment]
Alright. I've made the updates. Logs are now put into a sub-directory inside "Documents." Check the README for more info.

**Pull request merged**
