### PR TITLE
Notifications Second Pass

### LINKED ISSUE #37: Fix Repetitive Classifications Using Ask a Neighbor
By using the Ask a Neighbor component, it is possible for two users to loop each other into classifying the same subject multiple times. Although this would have to be done deliberately, the UI should restrict such a situation and show some indicator to the user that this cannot happen.

### LINKED ISSUE #38: Ask a neighbor user stories
Google doc here:
https://docs.google.com/document/d/1NZ3jtQrxBAuLyD_yY8oCQpdK1URhXn2fass_712XVgk/edit?usp=sharing

### PR DESCRIPTION
**Pull request by wgranger**
Describe your changes.
This PR makes changes on the touch table based on notification user stories. See issue linked below.

Closes #38 
Fixes #37 

# Review Checklist

- [x] Are tests passing?
- [x] Is the build free of output errors?

### CODE REVIEW

**Comment by wgranger** [comment]
This has been rebased and is ready for a review.

**Comment by noahmalmed** [comment]
New functionality look good. I think there may be a bug with the notification popup not resetting the away timer. It seemed like the away modal popped up almost right after I interacted with the notification pop up

**Comment by wgranger** [comment]
Confirmed. Looks like it isn't getting reset. I'll take care of it.

**Comment by wgranger** [comment]
Fixed. Also took care of a bug where User A could still accept an invite from User B even after User B has left the table.

**Comment by noahmalmed** [comment]
lgtm, merging

**Pull request merged**
