### PR TITLE
Style Classifier with Correct Sizing

### PR DESCRIPTION
**Pull request by wgranger**
With the previous PR, there were still a few issues remaining concerning sizing of the classifier on small screens vs. the large touchtable. This PR takes care of those issues and also adds the `Centerpiece` component messaging to users.

The setup should also be working, and I can walk you through that if needed.

### CODE REVIEW

**Comment by noahmalmed** [comment]
image

Looks like there are some sizing issues with the middle image cutting off some of the other views. Seems like you can just fix it by making the background of the center image transparent.

**Comment by noahmalmed** [comment]
Also looks like the bar that goes about "Help Classify the Galaxy" is going over the avatar circle. Is that correct?

Additionally it looks like the avatar circle is overlapping with the "Close workspace button"

**Comment by wgranger** [comment]
Alright. Changes made for your request. This should handle the avatar sizing correctly for multiple windows.

**Comment by noahmalmed** [comment]
Looks good! Thanks

**Pull request merged**
